### ISSUE TITLE
Not working on Cellular Networks but working on WiFi.

### ISSUE THREAD

**Issue by twisp007** [Magisk-Modules-Repo/magisk-google-dns#2]
I saw that as of v2.1, this module uses ip tables thus supporting cellular networks but it's not working for me. It's only working on WiFi.

I used "Extended test" dnsleaktest.com. On WiFi all the DNS servers listed are from google, but on cellular data, they are from my cellular service provider.

If there is a way/need to provide you logs, let me know.

**Comment by tfae** [comment]
There seems to be a problem with making it to work on mobile on certain devices.
I can't find a solution, so until someone jumps in and contribute with a working solution, there's nothing I can do.

I've updated the module info to reflect this difficult.
